### ISSUE TITLE
This doesn't work with Cassandra 3.x series

### ISSUE THREAD

**Issue by mattkanwisher** [wildengineer/cassandra-data-copy-tool#1]
Just an FYI for others looking at this

**Comment by wildengineer** [comment]
Thanks for the heads up.

**Comment by wildengineer** [comment]
The changes merged to develop in #4 updated spring data cassandra to 2.1.2-RELEASE. Cassandra 3 should be supported now. I will test and let you know.

**Comment by wildengineer** [comment]
#8 Updated the cassandra driver to be compatible with Cassandra 3.
